[package]
name = "mcrx-core"
version = "0.1.1"
edition = "2024"
license = "BSD-2-Clause"

[features]
default = []
metrics = []

[dependencies]
socket2 = "0.5"
bytes = "1"
thiserror = "1"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Networking_WinSock", "Win32_System_IO"] }
